name:                excel-lite
version:             0.1.0.0
github:              "CharlesTaylor7/excel-lite"
license:             BSD3
author:              "Charles Taylor"
maintainer:          "charlestaylor95@gmail.com"
copyright:           "2019 Charles Taylor"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CharlesTaylor7/excel-lite#readme>

dependencies:
- base >= 4.7 && < 5
- rio
- lens
- mtl
- parsec
- recursion-schemes
- reflex

default-extensions:
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - MonoLocalBinds
  - AllowAmbiguousTypes
  - ScopedTypeVariables
  - TypeApplications
  - LambdaCase
  - TupleSections
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - PartialTypeSignatures
  - RankNTypes
  - GADTs
  - FlexibleContexts
  - TypeFamilies

ghc-options:
  - -Wno-deprecations
  - -fwarn-incomplete-patterns
library:
  source-dirs: src

executables:
  excel-lite-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - excel-lite

tests:
  excel-lite-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - excel-lite
    - hspec
    - QuickCheck
